// cities.js

module.exports = [
    'Tokyo',
    'Delhi',
    'Shanghai',
    'São Paulo',
    'Mexico City',
    'Cairo',
    'Mumbai',
    'Beijing',
    'Dhaka',
    'Osaka',
    'New York',
    'Karachi',
    'Buenos Aires',
    'Chongqing',
    'Istanbul',
    'Kolkata',
    'Manila',
    'Lagos',
    'Rio de Janeiro',
    'Tianjin',
    'Kinshasa',
    'Guangzhou',
    'Los Angeles',
    'Moscow',
    'Shenzhen',
    'Lahore',
    'Bangalore',
    'Paris',
    'Bogotá',
    'Jakarta',
    'Chennai',
    'Lima',
    'Bangkok',
    'Seoul',
    'Nagoya',
    'Hyderabad',
    'London',
    'Tehran',
    'Chicago',
    'Chengdu',
    'Nanjing',
    'Wuhan',
    'Ho Chi Minh City',
    'Luanda',
    'Ahmedabad',
    'Kuala Lumpur',
    'Hong Kong',
    'Baghdad',
    'Toronto',
    'Santiago',
    'Riyadh',
    'Singapore',
    'Surat',
    'Madrid',
    'Suzhou',
    'Pune',
    'Harbin',
    'Houston',
    'Dallas',
    'Dar es Salaam',
    'Miami',
    'Belo Horizonte',
    'Singapore',
    'Philadelphia',
    'Atlanta',
    'Fukuoka',
    'Khartoum',
    'Barcelona',
    'Johannesburg',
    'Saint Petersburg',
    'Qingdao',
    'Dalian',
    'Washington, D.C.',
    'Yangon',
    'Alexandria',
    'Jinan',
    'Guadalajara',
    'Boston',
    'Melbourne',
    'Sydney',
    'Busan',
    'Phoenix',
    'Brasília',
    'Recife',
    'Hanoi',
    'Shantou',
    'San Francisco',
    'Detroit',
    'Montreal',
    'Berlin',
    'Porto Alegre',
    'Rome',
    'Brasilia',
    'Haiphong',
    'Medellín',
    'Monterrey',
    'Tashkent',
    'Cape Town',
    'Yangon'
];
